services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017 #puerto de mi contenerdor enlazado a mi puerto
    environment:
      - MONGODB_DATABASE=nest-pokemon
    volumes:
      - ./mongo:/data/db